version: '3.2'
services:
  mailchimp:
    image: bersling/mailchimp
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
      labels:
        - "traefik.frontend.rule=Host:mailchimp2.tsmean.com"
        - "traefik.port=52502"
        - "traefik.docker.network=traefik"
    ports:
      - "52502:52502"
    secrets:
      - mailchimp.json
    networks:
      - traefik

networks:
  traefik:
    external: true

secrets:
  mailchimp.json:
    file: ./secrets/mailchimp.json
